- name: Start ufw service
  service:
    name: ufw
    enabled: true
    state: started

- name: Enable ufw
  become: true
  ufw:
    state: enabled
    policy: allow

- name: ufw - enable forwarding
  become: true
  lineinfile:
    dest: /etc/default/ufw
    regexp: "^DEFAULT_FORWARD_POLICY="
    line: DEFAULT_FORWARD_POLICY="ACCEPT"

- name: ufw - Allow incoming VPN connection
  become: true
  ufw:
    direction: in
    proto: "{{openvpn_proto}}"
    to_port: "{{openvpn_port}}"
    rule: allow

- name: ufw - Accept packets from VPN tunnel adaptor
  become: true
  ufw:
    direction: in
    interface: tun0
    rule: allow

- name: ufw - setup nat table rules
  become: true
  blockinfile:
    dest: /etc/ufw/before.rules
    state: present
    insertbefore: \*filter
    block: |
      # OpenVPN config
      *nat
      :POSTROUTING ACCEPT [0:0]
      -A POSTROUTING -s {{openvpn_server_network}}/24 -j SNAT --to-source {{ansible_default_ipv4.address}}
      COMMIT
  notify:
    - restart ufw
