---
galaxy_info:
  author: Andrew Rothstein
  description: a role to download and install the docker binaries
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - jessie
    - name: Ubuntu
      versions:
        - xenial
    - name: Alpine
      versions:
        - all
  galaxy_tags:
    - docker
    - containers

dependencies:
  - src: andrewrothstein.unarchive-deps
    version: v1.0.9
  - src: andrewrothstein.bash
    version: v1.1.0
